<?php

declare(strict_types=1);

namespace OnMoon\OpenApiServerBundle\CodeGenerator\PhpParserGenerators;

use OnMoon\OpenApiServerBundle\CodeGenerator\Definitions\GeneratedFileDefinition;
use OnMoon\OpenApiServerBundle\CodeGenerator\Definitions\GeneratedInterfaceDefinition;
use OnMoon\OpenApiServerBundle\CodeGenerator\Definitions\ServiceInterfaceDefinition;
use function sprintf;

class InterfaceCodeGenerator extends CodeGenerator
{
    public function generate(GeneratedInterfaceDefinition $definition) : GeneratedFileDefinition
    {
        $fileBuilder = $this
            ->factory
            ->namespace($definition->getNamespace());

        $interfaceBuilder = $this
            ->factory
            ->interface($definition->getClassName())
            ->setDocComment(sprintf(self::AUTOGENERATED_WARNING, 'interface'));

        if ($definition->getExtends() !== null) {
            $interfaceBuilder->extend($definition->getExtends()->getClassName());
            $this->use($fileBuilder, $definition->getNamespace(), $definition->getExtends());
        }

        if ($definition instanceof ServiceInterfaceDefinition) {
            $methodBuilder = $this->factory->method($definition->getMethodName())->makePublic();
            if ($definition->getRequestType() !== null) {
                $this->use($fileBuilder, $definition->getNamespace(), $definition->getRequestType());

                $methodBuilder->addParam(
                    $this->factory->param('request')->setType($definition->getRequestType()->getClassName())
                );
                //ToDo: Add full docblock support
            }

            if ($definition->getResponseType() !== null) {
                $this->use($fileBuilder, $definition->getNamespace(), $definition->getResponseType());
                $methodBuilder->setReturnType($definition->getResponseType()->getClassName());
            } else {
                $methodBuilder->setReturnType('void');
            }

            if ($definition->getMethodDescription() !== null) {
                $methodBuilder->setDocComment($this->getDocComment([$definition->getMethodDescription()]));
            }

            $interfaceBuilder->addStmt($methodBuilder);
        }

        $fileBuilder = $fileBuilder->addStmt($interfaceBuilder);

        return new GeneratedFileDefinition(
            $definition,
            $this->printFile($fileBuilder)
        );
    }
}
